# https://docs.github.com/ja/actions/creating-actions/metadata-syntax-for-github-actions

name: "Run Test Plan at Autify for Mobile"
description: "Run a Test Plan at Autify for Mobile on GitHub Actions"
author: "Autify"

runs:
  using: "composite"
  steps:
    - name: Run Test Plan
      shell: bash
      id: run-test-plan-action
      run: >
        echo "hello"
