---
name: "web-run-test-plan-action"
description: "Runs a Test Plan to execute automated E2E tests on Autify for Web"
author: "Autify"

runs:
  using: composite
  steps:
    - name: "Run a Test Plan on Autify for Web"
      shell: bash
      id: run-test-plan-action
      run: >
        echo "hello"
